#!/bin/bash

# This will be the directory where you will store .json files for project
mkdir -p ~/automate # eg: project_backup.json
chmod +x cron_script backup_script
cp project_backup.json ~/automate/

crontab -l > cronfile
# cron job executing every 3rd day
echo "0 0 */3 * * $PWD/cron_script" >> cronfile
crontab cronfile

# Installation complete
