#!/bin/bash

# This will be the directory where you will store .json files for project
# eg: project_backup.json
mkdir -p ~/automate

crontab -l > cronfile
echo "0 0 */3 * * $PWD/cron.sh" >> cronfile
crontab cronfile

# Installation complete
